### PR TITLE
Added a way to use always the same jar

### PR DESCRIPTION
**Pull request by Lorenzo0111**
Hello, I'm a developer and I always use ServerJars to test my plugins. Every time I start a server for testing a plugin the updater will download the new jar. With this option I can always use the same server jar for every server instance. I think it will be very usefull for lots of users.

### CODE REVIEW

**Comment by SpraxDev** [comment]
I really like your idea and hopefully get to test it for the next release - Thanks for your contribution!

**Comment by SpraxDev** [comment]
Hi @Lorenzo0111 I took a look and while making some changes to ServerJars, I added your feature in the new dev build.

Would you mind trying it out? After the first start, it will update the config with the new options
[ServerJars-4.0.0-DEV.zip](https://github.com/ServerJars/updater/files/8192933/ServerJars-4.0.0-DEV.zip)

What your PR was missing, is an option to not have jar files deleted. So if you'd use two ServerJar instances with different Spigot versions, they would delete each others versions on setup

**Comment by Lorenzo0111** [comment]
> Hi @Lorenzo0111 I took a look and while making some changes to ServerJars, I added your feature in the new dev build.
> 
> Would you mind trying it out? After the first start, it will update the config with the new options [ServerJars-4.0.0-DEV.zip](https://github.com/ServerJars/updater/files/8192933/ServerJars-4.0.0-DEV.zip)
> 
> What your PR was missing, is an option to not have jar files deleted. So if you'd use two ServerJar instances with different Spigot versions, they would delete each others versions on setup

Hey, it doesn't work. I think that the problem is that you are setting the jarsDirectory property but reading the MinecraftJarDirectory one

**Comment by SpraxDev** [comment]
Yeah you are probably right, mb - I'll send a fresh build later, so maybe you would be able to test again. When I did my testing, I probably set the correct one manually

**Comment by Im-Fran** [comment]
Closing this. Implemented in #28

**Pull request closed without merging**
